# PyTorch 2D Tensors

## <a name="ackw"></a> Acknowledgements

The Python code for this notebook is edited for the course <a href="https://courses.edx.org/courses/course-v1:IBM+DL0110EN+3T2018/course/"> Deep Learning with Python and PyTorch</a> on <a href="https://www.edx.org/">edX</a>.

## <a name="overview"></a> Overview

<a href="https://pytorch.org/">PyTorch</a> is, at the time of writting, one of the most used frameworks for deep learing computations. Alongside its C++ implementation,
it exposes  a Python API to simlify its use. In this notebook we talk about the basic operations of the ```torch.tensor```. This class is one of the cornerstones of the framework. Concretely, we will see how to create 2D tensors.

## <a name="ekf"></a> PyTorch 2D tensors

### <a name="test_case_1"></a> Create tensors

In [1]:
import torch

In 2D tensors are essentially matrices. Create a 2D tensor

In [2]:
a = [[4,6,7], [1,2,3], [9,10,11]]
tensor = torch.tensor(a)

In [3]:
tensor.ndimension()

2

What is the shape of the tensor

In [4]:
tensor.shape

torch.Size([3, 3])

What is the size

In [6]:
tensor.size()

torch.Size([3, 3])

### <a name="test_case_2"></a>  Indexing & slicing


In [7]:
print(tensor)

tensor([[ 4,  6,  7],
        [ 1,  2,  3],
        [ 9, 10, 11]])


In [8]:
print(tensor[0][0])
print(tensor[1][1])
print(tensor[2][2])

tensor(4)
tensor(2)
tensor(11)


Access all elements in the first row

In [9]:
print(tensor[0, 0:3])

tensor([4, 6, 7])


Access all elements in the second row

In [10]:
print(tensor[1, 0:3])

tensor([1, 2, 3])


Access all elements in the first column

In [13]:
print(tensor[:3, 0])

tensor([4, 1, 9])


Access all elements in the last column

In [14]:
print(tensor[:3, 2])

tensor([ 7,  3, 11])


### <a name="test_case_3"></a>  Basic operations

In [15]:
u = torch.tensor([[1,1], [2,2]])
v = torch.tensor([[1,1], [2,2]])

The ```*``` operator performs element wise multiplication

In [17]:
product = u*v
product

tensor([[1, 1],
        [4, 4]])

The matrix multiplication is computed using the ```torch.mm(t1, t2)``` function

In [19]:
product = torch.mm(u, v)
product

tensor([[3, 3],
        [6, 6]])

### Computing gradients


## <a name="refs"></a> References

1. Eli Stevens, Luca Antiga, Thomas Viehmann, ```Deep Learning with PyTorch```, Manning Publications.
2. <a href="https://pytorch.org/tutorials/">PyTorch tutorials</a>
3. <a href="https://courses.edx.org/courses/course-v1:IBM+DL0110EN+3T2018/course/"> Deep Learning with Python and PyTorch</a>