# PyTorch Layers


* [Acknowledgements](#ackw)
* [Overview](#overview)
* [PyTorch layers](#ekf)
    * [Convolutional layers](#sub_sect_1)
    * [Linear layers](#sub_sect_2) 
* [References](#refs)

## <a name="ackw"></a> Acknowledgements

This notebook is edited from the article <a href="https://towardsdatascience.com/pytorch-layer-dimensions-what-sizes-should-they-be-and-why-4265a41e01fd">PyTorch layer dimensions: what size and why?</a> by Jake Krajewsky.

## <a name="overview"></a> Overview

## <a name="ekf"></a> PyTorch layers

In [1]:
import torch
import torch.nn as nn

## <a name="sub_sect_1"></a> Convolutional layers

We will work first wit a ```Conv2d``` layer. The class constructor  expects the following: ```(n_samples, channels, height, width)```. Thus  the ```Conv2d``` layer requires a 4-dim ```tensor```.

In [28]:

layer = nn.Conv2d(1, 1, 2, 2)
print(layer)

Conv2d(1, 1, kernel_size=(2, 2), stride=(2, 2))


In [29]:
x = torch.tensor([[0.2, 1.2], [1.2, 3.5]])
print(x)
print(x.shape)

tensor([[0.2000, 1.2000],
        [1.2000, 3.5000]])
torch.Size([2, 2])


In [30]:
x = x.unsqueeze(0)
print(x)
print(x.shape)

tensor([[[0.2000, 1.2000],
         [1.2000, 3.5000]]])
torch.Size([1, 2, 2])


In [31]:
x = x.unsqueeze(1)
print(x)
print(x.shape)

tensor([[[[0.2000, 1.2000],
          [1.2000, 3.5000]]]])
torch.Size([1, 1, 2, 2])


x = x.unsqueeze(2)
print(x)
print(x.shape)

Let's try to pass this data in a ```Conv2d``` layer

In [32]:
out = layer(x)
print(out.shape)

torch.Size([1, 1, 1, 1])


## <a name="sub_sect_2"></a> Linear layers

The PyTorch ```nn.Linear``` has the following constructor 

```
torch.nn.Linear(in_features: int, out_features: int, bias: bool = True)
```

Thus, the layer expects the number of input features as well as the number of output features to be specified. Let's see 

In [33]:
layer = nn.Linear(in_features=2, out_features=1)
print(layer)

Linear(in_features=2, out_features=1, bias=True)


In [34]:
x = torch.tensor([[0.2, 1.2], [1.2, 3.5]])
print(x)
print(x.shape)

tensor([[0.2000, 1.2000],
        [1.2000, 3.5000]])
torch.Size([2, 2])


In [35]:
out = layer(x)
print(out.shape)

torch.Size([2, 1])


In [37]:
print("Linear layer weights: {0}".format(layer.weight))

Linear layer weights: Parameter containing:
tensor([[-0.3015,  0.2372]], requires_grad=True)


The way the ```nn.Linear``` interprets the input tensor ```x``` is as two batches of two-features vectors. What happens when we want to pass the data as one batch? We can use ```view()``` to get ```[batch_size, num_features]```

In [39]:
batch_size = 1
x = x.view(batch_size, -1)
print(x)
print(x.shape)

tensor([[0.2000, 1.2000, 1.2000, 3.5000]])
torch.Size([1, 4])


## <a name="refs"></a> References