# PyTorch Tensors {#sec-pytorch-tensors}

## Overview

Numpy is a great framework, but it cannot utilize GPUs to accelerate its numerical computations. For modern deep neural networks, GPUs often provide speedups of 50x or greater. This inherent limitation of numpy, does not make it suitable for modern deep learning computations.

<a href="https://pytorch.org/">PyTorch</a> is, at the time of writting, one of the most used frameworks for deep learing computations. Alongside its C++ implementation,
it exposes  a Python API to simlify its use. In chapter we talk about the basic operations of the ```torch.tensor``` class. This class is one of the cornerstones of the framework. Tensors are the building blocks for data in PyTorch; neural networks take tensors as input and produce tensors as outputs. In addition,  all operations within a neural network or during optimization are operations between tensors. 
The presentation is not exhaustive as you can visit the <a href="https://pytorch.org/tutorials/">official tutorials</a> and get a deeper understanding.

## PyTorch tensors

A PyTorch tensor is conceptually identical to a numpy array: a tensor is an n-dimensional array. PyTorch provides many functions for operating on these tensors [4]. Behind the scenes, tensors can keep track of a computational graph and gradients this proves to be helpful when we want to compute the gradients in backpropagation pass. Unlike ```numpy```, PyTorch tensors can utilize GPUs to accelerate their numeric computations. To run a PyTorch tensor on GPU, you simply need to specify the correct device [4]. Let's see a few examples on how to use and manipulate ```torch.Tensors```.


### Create tensors

In [1]:
import torch
import numpy as np

The are various ways to create a tensor in PyTorch. Below we willustrate four of them:

In [2]:
x = torch.tensor([0,1,2,3,4])
y = torch.ones(4)
z = torch.FloatTensor([0,1,2,3,4])

np_array = np.array([1.0, 2.0, 3.0])
w = torch.from_numpy(np_array)



In [3]:
print(x)
print(y)

tensor([0, 1, 2, 3, 4])
tensor([1., 1., 1., 1.])


What's the size of the tensor?

In [4]:
x.size()

torch.Size([5])

Tensors can be multidimensional. We can figure out the dimension of a tensor via

In [5]:
x.ndimension()

1

Find out the type of the data that is stored in the tensor

In [6]:
x.dtype

torch.int64

Find out the type of the tensor

In [7]:
x.type()

'torch.LongTensor'

We can use ```torch.from_numpy(np.array)``` to convert from a ```numpy``` array to a ```torch.tensor```. 
Similarly, we can use ```tensor_inst.numpy()``` to get a ```numpy``` representation of the tensor:

In [8]:
w = torch.from_numpy(np_array)
new_np_array = w.numpy()
assert all(np_array == new_np_array)

print(new_np_array)

[1. 2. 3.]


----
**Remark**

In order to get the numpy representation of the tensor, the latter must be stored on the CPU. In this case this operation has almost zero cost.
Moreover, it also means that if we modify the numpy array will lead to a change in the originating tensor. 
However, If the tensor is allocated on the GPU, PyTorch will make a copy of the content of the tensor into a numpy array allocated on the CPU.

----

#### Indexing and slicing

Just like _numpy_ arrays, we can index and slice a ```torch.Tensor```. We can access an element using its zero-based index or assign a new value to it.

In [9]:
print(x[0])
print(y[1])
print(z[2])


tensor(0)
tensor(1.)
tensor(2.)


Notice that the output above is a ```tensor``` and not a primitive value as we may have expected. For tensors containing
just one element, we can use ```tensor.item()``` to access the actual value:

In [10]:
print(y[1].item())

1.0


Indexing can also be used to assign a new value to the corresponding position:

In [11]:
y[1] = 35.0

In [12]:
print(y[1].item())

35.0


We can ```stack``` tensors together and form a new tensor

In [15]:
tensor_list = []

for i in range(5):
    x = torch.tensor([0, 1, 2, 3, 4], dtype=torch.float32)
    tensor_list.append(x)
    
tensor_stack = torch.stack(tensor_list)

In [18]:
print(tensor_stack.shape)
print(f"Mean along columns: {torch.mean(tensor_stack, dim=0)}")
print(f"Mean along rows: {torch.mean(tensor_stack, dim=1)}")

torch.Size([5, 5])
Mean along columns: tensor([0., 1., 2., 3., 4.])
Mean along rows: tensor([2., 2., 2., 2., 2.])


### Two-dimensional tensors

PyTorch tensors need not be 1D. The framework supports multidimensional tensors. In 2D tensors are essentially matrices.
To a large extent working with multidimensional tensors is similar to working with 1D tensors.

In [16]:
a = [[4,6,7], [1,2,3], [9,10,11]]
q2d = torch.tensor(a)

In [17]:
q2d.ndimension()

2

What is the shape of the tensor

In [18]:
q2d.shape

torch.Size([3, 3])

What is the size

In [19]:
q2d.size()

torch.Size([3, 3])

####  Indexing & slicing

Indexing and slicing also works for higher dimensional tensors.

In [20]:
print(q2d)

tensor([[ 4,  6,  7],
        [ 1,  2,  3],
        [ 9, 10, 11]])


In [21]:
print(q2d[0][0])
print(q2d[1][1])
print(q2d[2][2])

tensor(4)
tensor(2)
tensor(11)


Access all elements in the first row

In [24]:
print(q2d[0, 0:3])

tensor([4, 6, 7])


Access all elements in the second row

In [10]:
print(tensor[1, 0:3])

tensor([1, 2, 3])


Access all elements in the first column

In [13]:
print(tensor[:3, 0])

tensor([4, 1, 9])


Access all elements in the last column

In [14]:
print(tensor[:3, 2])

tensor([ 7,  3, 11])


### <a name="test_case_3"></a>  Basic operations

In [15]:
u = torch.tensor([[1,1], [2,2]])
v = torch.tensor([[1,1], [2,2]])

The ```*``` operator performs element wise multiplication

In [17]:
product = u*v
product

tensor([[1, 1],
        [4, 4]])

The matrix multiplication is computed using the ```torch.mm(t1, t2)``` function

In [19]:
product = torch.mm(u, v)
product

tensor([[3, 3],
        [6, 6]])

Often we want to insert a unit axis into a tensor. We can do that using the ```unsqueeze``` method

### Computing gradients


----
**Remark** 

This feature of PyTorch enables us to define models simply by defining the
forward pass, computing a loss, and calling ```.backward()``` on the loss to
automatically compute the derivative of each of the parameters with
respect to that loss. In particular, we don’t have to worry about reusing the
same quantity multiple times in the forward pass  as this
simple example shows, gradients will automatically be computed correctly
once we call backward on the output of our computations.

----

## Using CUDA

So far we have been looking into PyTorch tensors by assuming that all the operations are performed on a CPU. 
In this section we will look into how to utilize a GPU. 

In [13]:
if torch.cuda.is_available():
    print("We do have CUDA support")
else:
    print("No CUDA support available")

We do have CUDA support


Assuming that there is GPU support on the underlying hardware you are using, we can transfer a 
PyTorch tensor to (one of) the GPUs availbale. All operations that will be performed on the tensor will be carried out using GPU-specific routines that come with PyTorch. This can be done by either creating a tensor explicitly on the available graphics unit or
by transfering an existing one:

In [14]:
x_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
y_gpu = y.to(device='cuda')

Either approach returns a new tensor that has the same numerical data, 
but stored in the RAM of the GPU, rather than in regular system RAM. Notice that if the machine we are using has more than on GPU cards available, we can choose which one we want to use

In [15]:
z_gpu = y.to(device='cuda:0')

For every tensor that is either transferred or instantiated on a GPU, the operations 
dictated will take place 
on the GPU

In [16]:
y_gpu = 3 * y_gpu

Given the computational model that GPUs adopt, we cannot mix and match CPU and GPUs easily:

In [17]:
x_cpu = y_gpu.to(device='cpu')
y_gpu = y_gpu + x_cpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

We can also use the shorthand methods ```cpu``` and ```cuda``` instead of the ```to``` method:

In [12]:
x_gpu = x_cpu.cuda()
y_cpu = y_gpu.cpu()

However, the ```to``` method has the added advantage that we can change the placement and the data type simultaneously by providing both ```device``` and ```dtype``` as arguments.

## Summary

In this chapter we introduced tensor objects and saw how to manipulate these with PyTorch. PyTorch is a very
versatile library with a large ecosystem. In the next chapter, we will concentrate how to handle 
tensors for images, tabular data, time series and text.

## <a name="refs"></a> References

1. Eli Stevens, Luca Antiga, Thomas Viehmann, ```Deep Learning with PyTorch```, Manning Publications.
2. <a href="https://pytorch.org/tutorials/">PyTorch tutorials</a>
3. <a href="https://courses.edx.org/courses/course-v1:IBM+DL0110EN+3T2018/course/"> Deep Learning with Python and PyTorch</a>
4. <a href="https://pytorch.org/tutorials/beginner/pytorch_with_examples.html">Learning PyTorch with Examples</a>