# PyTorch ```tensor```


## <a name="ackw"></a> Acknowledgements

The Python code for this notebook is edited for the course <a href="https://courses.edx.org/courses/course-v1:IBM+DL0110EN+3T2018/course/"> Deep Learning with Python and PyTorch</a> on <a href="https://www.edx.org/">edX</a>.

## <a name="overview"></a> Overview

<a href="https://pytorch.org/">PyTorch</a> is, at the time of writting, one of the most used frameworks for deep learing computations. Alongside its C++ implementation,
it exposes  a Python API to simlify its use. In this notebook we talk about the basic operations of the ```torch.tensor```. This class is one of the cornerstones of the framework. The presentation is not exhaustive as you can visit the <a href="https://pytorch.org/tutorials/">official tutorials</a> and get a deeper understanding.

## <a name="ekf"></a> PyTorch ```tensor```

Numpy is a great framework, but it cannot utilize GPUs to accelerate its numerical computations. For modern deep neural networks, GPUs often provide speedups of 50x or greater, so unfortunately numpy won’t be enough for modern deep learning. A PyTorch Tensor is conceptually identical to a numpy array: a Tensor is an n-dimensional array, and PyTorch provides many functions for operating on these Tensors [4]. Behind the scenes, Tensors can keep track of a computational graph and gradients, but they’re also useful as a generic tool for scientific computing.
Unlike ```numpy```, PyTorch Tensors can utilize GPUs to accelerate their numeric computations. To run a PyTorch Tensor on GPU, you simply need to specify the correct device [4].



### <a name="test_case_1"></a> Create tensors

In [17]:
import torch

Check if we use CUDA o not

In [18]:
if torch.cuda.is_available():
    print("We do have CUDA support")
else:
    print("No CUDA support available")

No CUDA support available


Create an 1D tensor

In [19]:
x = torch.tensor([0,1,2,3,4])

In [20]:
x.dtype

torch.int64

In [21]:
x.type()

'torch.LongTensor'

Find how many elemens the tensor has

torch.Size([5])

Find out how many dimensions the tensor has

1

Add an extra dimension

In [25]:
y_col = y.view(5,1)

### <a name="test_case_2"></a> 

Access the i-th tensor value using the subscript operator

In [26]:
y[0]

tensor(0.)

In [27]:
y[0] = 100.


In [28]:
y[0]

tensor(100.)

Slicing works the same way as in Python

In [29]:
y[1:4]

tensor([1., 2., 3.])

### <a name="test_case_3"></a> Basic operations

In [30]:
u = torch.tensor([1,0])
v = torch.tensor([0,1])

In [31]:
z = u + v
z

tensor([1, 1])

In [32]:
z = 2*v
z

tensor([0, 2])

The ```*``` operator performs element wise multiplication

In [33]:
z = u*v
z

tensor([0, 0])

The dot product is computed using the ```torch.dot(t1, t2)``` function

In [34]:
dot = torch.dot(u,v)
dot

tensor(0)

We can add a scalar to the tensor. ```PyTorch``` will add 1 to each element in ```u```. This is also known as <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">broadcasting</a>.

In [35]:
z = u + 1
z

tensor([2, 1])

### Computing gradients 

---
**Remark** 


This feature of PyTorch enables us to define models simply by defining the
forward pass, computing a loss, and calling ```.backward()``` on the loss to
automatically compute the derivative of each of the parameters with
respect to that loss. In particular, we don’t have to worry about reusing the
same quantity multiple times in the forward pass  as this
simple example shows, gradients will automatically be computed correctly
once we call backward on the output of our computations.

---

Often we want to insert a unit axis into a tensor. We can do that using the ```unsqueeze``` method

## <a name="refs"></a> References

1. Eli Stevens, Luca Antiga, Thomas Viehmann, ```Deep Learning with PyTorch```, Manning Publications.
2. <a href="https://pytorch.org/tutorials/">PyTorch tutorials</a>
3. <a href="https://courses.edx.org/courses/course-v1:IBM+DL0110EN+3T2018/course/"> Deep Learning with Python and PyTorch</a>
4. <a href="https://pytorch.org/tutorials/beginner/pytorch_with_examples.html">Learning PyTorch with Examples</a>