# PyTorch Tensors

## Overview

In this section, we will introduce tensors. In particular, we will see how we can create and manipulate tensors in PyTorch.
In particular, we will discuss basic operations of the ```torch.tensor```. This class is one of the cornerstones of the framework. 

## PyTorch tensors

Numpy is a great framework, but it cannot utilize GPUs to accelerate its numerical computations. For modern deep neural networks, GPUs often provide speedups of 50x or greater. This is something that at the time of writing ```numpy``` arrays simply cannot achieve. A PyTorch Tensor is conceptually identical to a numpy array: a Tensor is an n-dimensional array, and PyTorch provides many functions for operating on these Tensors [4]. Behind the scenes, Tensors can keep track of a computational graph and gradients this proves to be helpful when we want to compute the gradients in backpropagation pass..
Unlike ```numpy```, PyTorch Tensors can utilize GPUs to accelerate their numeric computations. To run a PyTorch Tensor on GPU, you simply need to specify the correct device [4]. Let's see a few examples on how to use and manipulate ```torch.Tensors```.


### Create tensors

In [15]:
import torch
import numpy as np

In [16]:
x = torch.tensor([0,1,2,3,4])

What's the size of the tensor?

In [17]:
x.size()

torch.Size([5])

Tensors can be multidimensional. We can figure out the dimension of a tensor via

In [18]:
x.ndimension()

1

Find out the type of the data that is stored in the tensor

In [19]:
x.dtype

torch.int64

Find out the type of the tensor

In [20]:
x.type()

'torch.LongTensor'

Create a tensor of a certain type i.e. ```FloatTensor```

In [21]:
y = torch.FloatTensor([0,1,2,3,4])

We can use ```torch.from_numpy(np.array)``` to convert from a ```numpy``` array to a ```torch.tensor```. 
Similarly, we can use ```tensor_inst.numpy()``` to get a ```numpy``` representation of the tensor:

In [24]:
np_array = np.array([1.0, 2.0, 3.0])
torch_tensor = torch.from_numpy(np_array)
new_np_array = torch_tensor.numpy()
assert all(np_array == new_np_array)

print(new_np_array)

[1. 2. 3.]


### Indexing & slicing

Just like _numpy_ arrays, we can index and slice a ```torch.Tensor```

In 2D tensors are essentially matrices. Create a 2D tensor

In [2]:
a = [[4,6,7], [1,2,3], [9,10,11]]
tensor = torch.tensor(a)

In [3]:
tensor.ndimension()

2

What is the shape of the tensor

In [4]:
tensor.shape

torch.Size([3, 3])

What is the size

In [6]:
tensor.size()

torch.Size([3, 3])

### <a name="test_case_2"></a>  Indexing & slicing


In [7]:
print(tensor)

tensor([[ 4,  6,  7],
        [ 1,  2,  3],
        [ 9, 10, 11]])


In [8]:
print(tensor[0][0])
print(tensor[1][1])
print(tensor[2][2])

tensor(4)
tensor(2)
tensor(11)


Access all elements in the first row

In [9]:
print(tensor[0, 0:3])

tensor([4, 6, 7])


Access all elements in the second row

In [10]:
print(tensor[1, 0:3])

tensor([1, 2, 3])


Access all elements in the first column

In [13]:
print(tensor[:3, 0])

tensor([4, 1, 9])


Access all elements in the last column

In [14]:
print(tensor[:3, 2])

tensor([ 7,  3, 11])


### <a name="test_case_3"></a>  Basic operations

In [15]:
u = torch.tensor([[1,1], [2,2]])
v = torch.tensor([[1,1], [2,2]])

The ```*``` operator performs element wise multiplication

In [17]:
product = u*v
product

tensor([[1, 1],
        [4, 4]])

The matrix multiplication is computed using the ```torch.mm(t1, t2)``` function

In [19]:
product = torch.mm(u, v)
product

tensor([[3, 3],
        [6, 6]])

### Computing gradients


## <a name="refs"></a> References

1. Eli Stevens, Luca Antiga, Thomas Viehmann, ```Deep Learning with PyTorch```, Manning Publications.
2. <a href="https://pytorch.org/tutorials/">PyTorch tutorials</a>
3. <a href="https://courses.edx.org/courses/course-v1:IBM+DL0110EN+3T2018/course/"> Deep Learning with Python and PyTorch</a>
4. <a href="https://pytorch.org/tutorials/beginner/pytorch_with_examples.html">Learning PyTorch with Examples</a>